services:
  smart-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: smart-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./src:/usr/share/nginx/html/src
    restart: unless-stopped